/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mephi.b22901.ekzamen;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.openxml4j.exceptions.InvalidOperationException;
import mephi.b22901.ekzamen.operations.ExcelImport;
import mephi.b22901.ekzamen.operations.ReportGenerator;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 *
 * @author ivis2
 */
public class MainGUI extends javax.swing.JFrame {
    private ArrayList<Group> groups;
    private File varFolder;
    private Group chosenGroup;
    private int varNum;
     

    /**
     * Creates new form Interface
     */
    public MainGUI() {
        initComponents();
         setContentPane(mainPanel);
        setTitle("Создание отчета о работах студентов");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(700, 400);
        setLocationRelativeTo(null);
        setVisible(true);
        createGroupReportButton.setEnabled(false);
        deleteRateButton.setEnabled(false);
        noWorkButton.setEnabled(false);
        openVarButton.setEnabled(false);
        importVarintButton.setEnabled(false);
        chooserGroupComboBox.setEnabled(false);
    }
    private final JFileChooser jFileChooser = new JFileChooser();
    private final JFileChooser jFolderChooser = new JFileChooser();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        firstStepLabel = new javax.swing.JLabel();
        secondStepLabel = new javax.swing.JLabel();
        thirdStepLabel = new javax.swing.JLabel();
        importStidentsButton = new javax.swing.JButton();
        importVarintButton = new javax.swing.JButton();
        chooserGroupComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        openVarButton = new javax.swing.JButton();
        noWorkButton = new javax.swing.JButton();
        deleteRateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentInfoList = new javax.swing.JList();
        createGroupReportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstStepLabel.setText("1 шаг");

        secondStepLabel.setText("2 шаг");

        thirdStepLabel.setText("3 шаг");

        importStidentsButton.setText("Импорт Студентов");
        importStidentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importStidentsButtonActionPerformed(evt);
            }
        });

        importVarintButton.setText("Импорт Варианта");
        importVarintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importVarintButtonActionPerformed(evt);
            }
        });

        chooserGroupComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Группа" }));
        chooserGroupComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserGroupComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("4 шаг");

        openVarButton.setText("Выставление оценки");
        openVarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openVarButtonActionPerformed(evt);
            }
        });

        noWorkButton.setText("Нет работы");
        noWorkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noWorkButtonActionPerformed(evt);
            }
        });

        deleteRateButton.setText("Удаление оценки ");
        deleteRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRateButtonActionPerformed(evt);
            }
        });

        studentInfoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Здесь будет список студентов" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        studentInfoList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                studentInfoListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(studentInfoList);

        createGroupReportButton.setText("Отчёт по группе");
        createGroupReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstStepLabel)
                            .addComponent(secondStepLabel)
                            .addComponent(thirdStepLabel))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(importStidentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(importVarintButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chooserGroupComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(openVarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noWorkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteRateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createGroupReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstStepLabel)
                    .addComponent(importStidentsButton)
                    .addComponent(jLabel1)
                    .addComponent(openVarButton))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondStepLabel)
                    .addComponent(importVarintButton)
                    .addComponent(noWorkButton))
                .addGap(21, 21, 21)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdStepLabel)
                    .addComponent(chooserGroupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteRateButton))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(createGroupReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importStidentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importStidentsButtonActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Students.xlsx", "xlsx");
        jFileChooser.setFileFilter(filter);

        int result = jFileChooser.showDialog(null, "Выбрать файл:");
        if (result != JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(MainGUI.this, "Файл не выбран");
            return;
        }

        File file = jFileChooser.getSelectedFile();
        if (file == null || !file.getName().equals("Students.xlsx")) {
            JOptionPane.showMessageDialog(MainGUI.this, "Пожалуйста, выберите файл Students.xlsx");
            return;
        }

        try {
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
            groups = ExcelImport.importStudents(file);
            for (Group group : groups) {
                comboBoxModel.addElement(group.getName());
            }
            chooserGroupComboBox.setModel(comboBoxModel);
            JOptionPane.showMessageDialog(MainGUI.this, "Студенты импортированы");
        } catch (IOException | InvalidFormatException ex) {
            JOptionPane.showMessageDialog(MainGUI.this, "Ошибка при импорте файла");
        }

        importVarintButton.setEnabled(true);
    }//GEN-LAST:event_importStidentsButtonActionPerformed

    private void importVarintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importVarintButtonActionPerformed
        try {
            jFolderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            jFolderChooser.showDialog(null, "Выбрать папку:");
            varFolder = jFolderChooser.getSelectedFile();
            JOptionPane.showMessageDialog(MainGUI.this, "Выбрана папка " + varFolder.getName());
        } catch (IllegalArgumentException | NullPointerException exception) {
            JOptionPane.showMessageDialog(MainGUI.this, "Папка не выбрана");
        }
        createGroupReportButton.setEnabled(true);
        noWorkButton.setEnabled(true);
        openVarButton.setEnabled(true);
        chooserGroupComboBox.setEnabled(true);
    }//GEN-LAST:event_importVarintButtonActionPerformed

    private void chooserGroupComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserGroupComboBoxActionPerformed
        DefaultListModel<Student> listModel = new DefaultListModel<>();
        
        String groupName = (String) chooserGroupComboBox.getSelectedItem();
        chosenGroup = groups.stream().filter(group1 -> Objects.equals(group1.getName(), groupName)).findFirst().get();
        for (Student student : chosenGroup.getStudents()) {
            listModel.addElement(student);
        }
        studentInfoList.setModel(listModel);
        studentInfoList.setSelectedIndex(0);
        createGroupReportButton.setEnabled(true);
    }//GEN-LAST:event_chooserGroupComboBoxActionPerformed

    private void noWorkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noWorkButtonActionPerformed
        StudentResult noWorkReport = new StudentResult();
        noWorkReport.setHasNoWork(true);
        chosenGroup.getStudents().get(studentInfoList.getSelectedIndex()).setReport(noWorkReport);
        updateStudentsList();
    }//GEN-LAST:event_noWorkButtonActionPerformed

    private void openVarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openVarButtonActionPerformed
        Student student = (Student) studentInfoList.getSelectedValue();
            if (student != null) {
                varNum = student.getVariant();
                try {
                    String path = varFolder.getPath() + "\\" + varNum + ".xlsx";
                    Variant variant = ExcelImport.importVariant(path);
                    StudentTaskRate estimation = new StudentTaskRate(variant, student, this);
                    setEnabled(false);
                    groups.get(chooserGroupComboBox.getSelectedIndex()).getStudents().get(studentInfoList.getSelectedIndex())
                            .setReport(estimation.getReport());
                } catch (IOException | InvalidOperationException | NullPointerException ex) {
                    JOptionPane.showMessageDialog(MainGUI.this, "Не найден файл варианта");
                }
            } else JOptionPane.showMessageDialog(MainGUI.this, "Студент не выбран");
            updateStudentsList();
    }//GEN-LAST:event_openVarButtonActionPerformed

    private void createGroupReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupReportButtonActionPerformed
        if (chosenGroup.getStudents().stream().anyMatch(student -> student.getReport() == null)) {
            JOptionPane.showMessageDialog(MainGUI.this, "Не все студенты оценены");
            return;
        }
        Object[] formats = {"Excel (.xlsx)", "Текстовый файл (.txt)"};
        int formatChoice = JOptionPane.showOptionDialog(
            MainGUI.this,
            "Выберите формат отчета",
            "Формат отчета",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            formats,
            formats[0]
        );

        if (formatChoice == JOptionPane.CLOSED_OPTION) {
            return;
        }

        ReportGenerator.Format format;
        if (formatChoice == 0) {
            format = ReportGenerator.Format.EXCEL;
        } else {
            format = ReportGenerator.Format.TXT;
        }
        String end;
        if (format == ReportGenerator.Format.EXCEL) {
            end = ".xlsx";
        } else {
            end = ".txt";
        }

        File selectedFolder;
        try {
            jFolderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            jFolderChooser.setDialogTitle("Выберите папку для сохранения отчета");

            if (jFolderChooser.showDialog(null, "Выбрать") != JFileChooser.APPROVE_OPTION) {
                return;
            }

            selectedFolder = jFolderChooser.getSelectedFile();
            JOptionPane.showMessageDialog(MainGUI.this, "Выбрана папка: " + selectedFolder.getName());
        } catch (IllegalArgumentException | NullPointerException exception) {
            JOptionPane.showMessageDialog(MainGUI.this, "Папка не выбрана");
            return;
        }

        String fileName = "Отчет_группы_" + chosenGroup.getName() + end;
        File reportFile = new File(selectedFolder, fileName);

        try {
            ReportGenerator.generateGroupReport(chosenGroup, reportFile, format);
            JOptionPane.showMessageDialog(MainGUI.this, 
                "Отчет успешно сохранен в:\n" + reportFile.getAbsolutePath());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(MainGUI.this, 
                "Ошибка при создании отчета:\n" + ex.getMessage(),
                "Ошибка", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createGroupReportButtonActionPerformed

    private void deleteRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRateButtonActionPerformed
        int chosenStudentIndex = studentInfoList.getSelectedIndex();
        Student chosenStudent = chosenGroup.getStudents().get(chosenStudentIndex);
        chosenStudent.setReport(null);
        updateStudentsList();
    }//GEN-LAST:event_deleteRateButtonActionPerformed

    private void studentInfoListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_studentInfoListValueChanged
        int chosenStudentIndex = studentInfoList.getSelectedIndex();
            try {
                Student chosenStudent = chosenGroup.getStudents().get(chosenStudentIndex);
                if (chosenStudent.getReport() != null) {
                    openVarButton.setEnabled(!chosenStudent.getReport().isHasNoWork());
                    openVarButton.setText("Редактировать оценку");
                    deleteRateButton.setEnabled(true);
                    noWorkButton.setEnabled(false);
                } else {
                    openVarButton.setEnabled(true);
                    openVarButton.setText("Оценить работу");
                    deleteRateButton.setEnabled(false);
                    noWorkButton.setEnabled(true);
                }
            } catch (IndexOutOfBoundsException exception) {
                System.out.println("Нет выбранного значения");
            }

    }//GEN-LAST:event_studentInfoListValueChanged

    /**
     * @param args the command line arguments
     */
    public void updateStudentsList() {
        DefaultListModel<Student> listModel = new DefaultListModel<>();
        for (Student student : chosenGroup.getStudents()) {
            listModel.addElement(student);
        }
        studentInfoList.setModel(listModel);
        studentInfoList.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooserGroupComboBox;
    private javax.swing.JButton createGroupReportButton;
    private javax.swing.JButton deleteRateButton;
    private javax.swing.JLabel firstStepLabel;
    private javax.swing.JButton importStidentsButton;
    private javax.swing.JButton importVarintButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton noWorkButton;
    private javax.swing.JButton openVarButton;
    private javax.swing.JLabel secondStepLabel;
    private javax.swing.JList studentInfoList;
    private javax.swing.JLabel thirdStepLabel;
    // End of variables declaration//GEN-END:variables
}
