/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mephi.b22901.ekzamen;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.openxml4j.exceptions.InvalidOperationException;
import mephi.b22901.ekzamen.operations.ExcelImport;
import mephi.b22901.ekzamen.operations.ReportGenerator;
import mephi.b22901.ekzamen.operations.ReportGenerator.Format;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 * Графический интерфейс для импорта студентов и вариантов,
 * оценки работ студентов и генерации отчетов.
 * Использует Swing-компоненты для взаимодействия с пользователем.
 * @author Иван Исаев
 */
public class MainGUI extends javax.swing.JFrame {
    private ArrayList<Group> groups;
    private File varFolder;
    private Group chosenGroup;
    private int varNum;
     

    /**
     * Создает новый интерфейс приложения,
     * инициализирует компоненты и настраивает окно.
     */
    public MainGUI() {
        initComponents();
         setContentPane(mainPanel);
        setTitle("Создание отчета о работах студентов");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(700, 400);
        setLocationRelativeTo(null);
        setVisible(true);
        createGroupReportButton.setEnabled(false);
        deleteRateButton.setEnabled(false);
        noWorkButton.setEnabled(false);
        openVarButton.setEnabled(false);
        importVarintButton.setEnabled(false);
        chooserGroupComboBox.setEnabled(false);
        createPersonReportButton.setEnabled(false);
        createAllReportButton.setEnabled(false);
    }
    private final JFileChooser jFileChooser = new JFileChooser();
    private final JFileChooser jFolderChooser = new JFileChooser();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        firstStepLabel = new javax.swing.JLabel();
        secondStepLabel = new javax.swing.JLabel();
        thirdStepLabel = new javax.swing.JLabel();
        importStidentsButton = new javax.swing.JButton();
        importVarintButton = new javax.swing.JButton();
        chooserGroupComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        openVarButton = new javax.swing.JButton();
        noWorkButton = new javax.swing.JButton();
        deleteRateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentInfoList = new javax.swing.JList();
        createGroupReportButton = new javax.swing.JButton();
        createPersonReportButton = new javax.swing.JButton();
        createAllReportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstStepLabel.setText("1 шаг");

        secondStepLabel.setText("2 шаг");

        thirdStepLabel.setText("3 шаг");

        importStidentsButton.setText("Импорт Студентов");
        importStidentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importStidentsButtonActionPerformed(evt);
            }
        });

        importVarintButton.setText("Импорт Варианта");
        importVarintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importVarintButtonActionPerformed(evt);
            }
        });

        chooserGroupComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Группа" }));
        chooserGroupComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserGroupComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("4 шаг");

        openVarButton.setText("Выставление оценки");
        openVarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openVarButtonActionPerformed(evt);
            }
        });

        noWorkButton.setText("Нет работы");
        noWorkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noWorkButtonActionPerformed(evt);
            }
        });

        deleteRateButton.setText("Удаление оценки ");
        deleteRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRateButtonActionPerformed(evt);
            }
        });

        studentInfoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Здесь будет список студентов" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        studentInfoList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                studentInfoListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(studentInfoList);

        createGroupReportButton.setText("Отчёт по группе");
        createGroupReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupReportButtonActionPerformed(evt);
            }
        });

        createPersonReportButton.setText("Отчёт по человеку");
        createPersonReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPersonReportButtonActionPerformed(evt);
            }
        });

        createAllReportButton.setText("Отчёт по потоку");
        createAllReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAllReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstStepLabel)
                            .addComponent(secondStepLabel)
                            .addComponent(thirdStepLabel))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(importStidentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(importVarintButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chooserGroupComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(openVarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noWorkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteRateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createGroupReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createPersonReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAllReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstStepLabel)
                    .addComponent(importStidentsButton)
                    .addComponent(jLabel1)
                    .addComponent(openVarButton))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondStepLabel)
                    .addComponent(importVarintButton)
                    .addComponent(noWorkButton))
                .addGap(21, 21, 21)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdStepLabel)
                    .addComponent(chooserGroupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteRateButton))
                .addGap(29, 29, 29)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(createGroupReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(createPersonReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(createAllReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Обрабатывает выбор Excel-файла со списками студентов
     * и импортирует данные о группах и студентах.
     *
     * @param evt Событие выбора файла.
     */
    private void importStidentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importStidentsButtonActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Students.xlsx", "xlsx");
        jFileChooser.setFileFilter(filter);

        try {
            File jarDir = new File(MainGUI.class
                .getProtectionDomain()
                .getCodeSource()
                .getLocation()
                .toURI())
                .getParentFile();

            jFileChooser.setCurrentDirectory(jarDir);
        } catch (Exception e) {
            jFileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        }
        
        int result = jFileChooser.showDialog(null, "Выбрать файл:");
        if (result != JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(MainGUI.this, "Файл не выбран");
            return;
        }

        File file = jFileChooser.getSelectedFile();
        if (file == null || !file.getName().equals("Students.xlsx")) {
            JOptionPane.showMessageDialog(MainGUI.this, "Пожалуйста, выберите файл Students.xlsx");
            return;
        }

        try {
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
            groups = ExcelImport.importStudents(file);
            for (Group group : groups) {
                comboBoxModel.addElement(group.getName());
            }
            chooserGroupComboBox.setModel(comboBoxModel);
            JOptionPane.showMessageDialog(MainGUI.this, "Студенты импортированы");
        } catch (IOException | InvalidFormatException ex) {
            JOptionPane.showMessageDialog(MainGUI.this, "Ошибка при импорте файла");
        }

        importVarintButton.setEnabled(true);
    }//GEN-LAST:event_importStidentsButtonActionPerformed
    /**
     * Обрабатывает выбор папки с файлами вариантов заданий.
     *
     * @param evt Событие выбора папки.
     */
    private void importVarintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importVarintButtonActionPerformed
        try {
            try {
                File jarDir = new File(MainGUI.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getParentFile();

                jFolderChooser.setCurrentDirectory(jarDir);
            } catch (Exception e) {
                jFolderChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
            }
            jFolderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            jFolderChooser.showDialog(null, "Выбрать папку:");
            varFolder = jFolderChooser.getSelectedFile();
            if (varFolder != null) {
                JOptionPane.showMessageDialog(MainGUI.this, "Выбрана папка " + varFolder.getName());
            } else {
                JOptionPane.showMessageDialog(MainGUI.this, "Папка не выбрана");
            }
        } catch (IllegalArgumentException | NullPointerException exception) {
            JOptionPane.showMessageDialog(MainGUI.this, "Папка не выбрана");
        }
        createGroupReportButton.setEnabled(true);
        noWorkButton.setEnabled(true);
        openVarButton.setEnabled(true);
        chooserGroupComboBox.setEnabled(true);
        createPersonReportButton.setEnabled(true);
        createAllReportButton.setEnabled(true);
    }//GEN-LAST:event_importVarintButtonActionPerformed
    /**
     * Обновляет список студентов в интерфейсе при выборе группы.
     *
     * @param evt Событие выбора группы.
     */
    private void chooserGroupComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserGroupComboBoxActionPerformed
        DefaultListModel<Student> listModel = new DefaultListModel<>();
        
        String groupName = (String) chooserGroupComboBox.getSelectedItem();
        chosenGroup = groups.stream().filter(group1 -> Objects.equals(group1.getName(), groupName)).findFirst().get();
        for (Student student : chosenGroup.getStudents()) {
            listModel.addElement(student);
        }
        studentInfoList.setModel(listModel);
        studentInfoList.setSelectedIndex(0);
        createGroupReportButton.setEnabled(true);
    }//GEN-LAST:event_chooserGroupComboBoxActionPerformed
    /**
     * Устанавливает для выбранного студента отметку об отсутствии работы.
     *
     * @param evt Событие нажатия кнопки.
     */
    private void noWorkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noWorkButtonActionPerformed
        StudentResult noWorkReport = new StudentResult();
        noWorkReport.setHasNoWork(true);
        chosenGroup.getStudents().get(studentInfoList.getSelectedIndex()).setReport(noWorkReport);
        updateStudentsList();
    }//GEN-LAST:event_noWorkButtonActionPerformed
    /**
     * Открывает вариант выбранного студента для оценки.
     *
     * @param evt Событие нажатия кнопки.
     */
    private void openVarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openVarButtonActionPerformed
        Student student = (Student) studentInfoList.getSelectedValue();
            if (student != null) {
                varNum = student.getVariant();
                try {
                    String path = varFolder.getPath() + "\\" + varNum + ".xlsx";
                    Variant variant = ExcelImport.importVariant(path);
                    StudentTaskRate estimation = new StudentTaskRate(variant, student, this);
                    setEnabled(false);
                    groups.get(chooserGroupComboBox.getSelectedIndex()).getStudents().get(studentInfoList.getSelectedIndex())
                            .setReport(estimation.getReport());
                } catch (IOException | InvalidOperationException | NullPointerException ex) {
                    JOptionPane.showMessageDialog(MainGUI.this, "Не найден файл варианта");
                }
            } else JOptionPane.showMessageDialog(MainGUI.this, "Студент не выбран");
            updateStudentsList();
    }//GEN-LAST:event_openVarButtonActionPerformed
    /**
    * Генерирует отчет по выбранной группе студентов.
    * Проверяет, что все студенты оценены, и сохраняет отчет.
    *
    * @param evt Событие нажатия кнопки.
    */
    private void createGroupReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupReportButtonActionPerformed
         if (chosenGroup.getStudents().stream().anyMatch(student -> student.getReport() == null)) {
            JOptionPane.showMessageDialog(this, "Не все студенты оценены");
            return;
        }

        int passingGrade = getPassingGradeFromUser();
        if (passingGrade < 0) return;

        Format format = showFormatDialog();
        if (format == null) return;

        File file = chooseSaveLocation("Отчет_группы_" + chosenGroup.getName(), format);
        if (file == null) return;

        try {
            ReportGenerator.generateGroupReport(chosenGroup, file, format, passingGrade);
            showSuccessMessage(file);
        } catch (IOException e) {
            showErrorMessage("Не удалось сохранить отчет:\n" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_createGroupReportButtonActionPerformed
    /**
     * Удаляет оценку у выбранного студента.
     *
     * @param evt Событие нажатия кнопки.
     */
    private void deleteRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRateButtonActionPerformed
        int chosenStudentIndex = studentInfoList.getSelectedIndex();
        Student chosenStudent = chosenGroup.getStudents().get(chosenStudentIndex);
        chosenStudent.setReport(null);
        updateStudentsList();
    }//GEN-LAST:event_deleteRateButtonActionPerformed
    /**
     * Обновляет состояние кнопок и списка студентов
     * при изменении выбранного студента.
     *
     * @param evt Событие выбора элемента списка студентов.
     */
    private void studentInfoListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_studentInfoListValueChanged
        int chosenStudentIndex = studentInfoList.getSelectedIndex();
            try {
                Student chosenStudent = chosenGroup.getStudents().get(chosenStudentIndex);
                if (chosenStudent.getReport() != null) {
                    openVarButton.setEnabled(!chosenStudent.getReport().isHasNoWork());
                    openVarButton.setText("Редактировать оценку");
                    deleteRateButton.setEnabled(true);
                    noWorkButton.setEnabled(false);
                } else {
                    openVarButton.setEnabled(true);
                    openVarButton.setText("Оценить работу");
                    deleteRateButton.setEnabled(false);
                    noWorkButton.setEnabled(true);
                }
            } catch (IndexOutOfBoundsException exception) {
                System.out.println("Нет выбранного значения");
            }
    }//GEN-LAST:event_studentInfoListValueChanged
    /**
     * Генерирует персональный отчет по выбранному студенту.
     *
     * @param evt Событие нажатия кнопки.
     */
    private void createPersonReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPersonReportButtonActionPerformed
         Student student = (Student) studentInfoList.getSelectedValue();
        if (student == null) {
            JOptionPane.showMessageDialog(this, "Студент не выбран");
            return;
        }

        if (student.getReport() == null) {
            JOptionPane.showMessageDialog(this, "Работа студента не оценена");
            return;
        }

        int passingGrade = getPassingGradeFromUser();
        if (passingGrade < 0) return;

        Format format = showFormatDialog();
        if (format == null) return;

        File file = chooseSaveLocation("Отчет_" + student.getFIO(), format);
        if (file == null) return;

        try {
            ReportGenerator.generateStudentReport(student, chosenGroup, file, format, passingGrade);
            showSuccessMessage(file);
        } catch (IOException e) {
            showErrorMessage("Не удалось сохранить отчет:\n" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_createPersonReportButtonActionPerformed
    /**
     * Генерирует сводный отчет по всем группам.
     * Проверяет, что все студенты оценены, и сохраняет отчет.
     *
     * @param evt Событие нажатия кнопки.
     */
    private void createAllReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAllReportButtonActionPerformed
        for (Group group : groups) {
            for (Student student : group.getStudents()) {
                if (student.getReport() == null) {
                    JOptionPane.showMessageDialog(this, "Не все студенты оценены");
                    return;
                }
            }
        }
        int passingGrade = getPassingGradeFromUser();
        if (passingGrade < 0) {
            return;
        }

        ReportGenerator.Format format = showFormatDialog();
        if (format == null) {
            return;
        }

        File file = chooseSaveLocation("Сводный_отчет", format);
        if (file == null) {
            return; 
        }

        try {
            ReportGenerator.generateAllGroupsReport(groups, file, format, passingGrade);
            showSuccessMessage(file);
        } catch (IOException e) {
            showErrorMessage("Не удалось сохранить отчет:\n" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_createAllReportButtonActionPerformed
    /**
     * Обновляет список студентов текущей выбранной группы.
     */
    public void updateStudentsList() {
        DefaultListModel<Student> listModel = new DefaultListModel<>();
        for (Student student : chosenGroup.getStudents()) {
            listModel.addElement(student);
        }
        studentInfoList.setModel(listModel);
        studentInfoList.setSelectedIndex(0);
    }
    /**
     * Запрашивает у пользователя минимальный проходной балл.
     *
     * @return Введенный проходной балл или -1, если ввод некорректен.
     */
    private int getPassingGradeFromUser() {
    try {
            int grade = Integer.parseInt(JOptionPane.showInputDialog(
                this, "Введите минимальный проходной балл:", "15"));
            if (grade < 0) {
                JOptionPane.showMessageDialog(this, "Балл не может быть отрицательным");
                return -1;
            }
            return grade;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Необходимо ввести целое число");
            return -1;
        }
    }
    /**
     * Отображает диалог выбора формата отчета.
     *
     * @return Выбранный формат отчета или {@code null}, если выбор отменен.
     */
    private Format showFormatDialog() {
        Object[] options = {"Excel (.xlsx)", "Текстовый файл (.txt)"};
        int choice = JOptionPane.showOptionDialog(
            this, "Выберите формат отчета", "Формат отчета",
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, options, options[0]);

        if (choice == 0) return Format.EXCEL;
        if (choice == 1) return Format.TXT;
        return null;
    }
    /**
     * Отображает диалог для выбора папки сохранения отчета.
     *
     * @param baseName Базовое имя файла отчета.
     * @param format Формат отчета.
     * @return Файл для сохранения или {@code null}, если выбор отменен.
     */
    private File chooseSaveLocation(String baseName, Format format) {
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (jFileChooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return null;
        }
        String extension = format == Format.EXCEL ? ".xlsx" : ".txt";
        return new File(jFileChooser.getSelectedFile(), baseName + extension);
    }
    /**
     * Показывает сообщение об успешном сохранении отчета.
     *
     * @param file Файл сохраненного отчета.
     */
    private void showSuccessMessage(File file) {
        JOptionPane.showMessageDialog(this, 
            "Отчет успешно сохранен:\n" + file.getAbsolutePath());
    }
    /**
     * Показывает сообщение об ошибке.
     *
     * @param message Текст ошибки.
     */
    private void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Ошибка", JOptionPane.ERROR_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooserGroupComboBox;
    private javax.swing.JButton createAllReportButton;
    private javax.swing.JButton createGroupReportButton;
    private javax.swing.JButton createPersonReportButton;
    private javax.swing.JButton deleteRateButton;
    private javax.swing.JLabel firstStepLabel;
    private javax.swing.JButton importStidentsButton;
    private javax.swing.JButton importVarintButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton noWorkButton;
    private javax.swing.JButton openVarButton;
    private javax.swing.JLabel secondStepLabel;
    private javax.swing.JList studentInfoList;
    private javax.swing.JLabel thirdStepLabel;
    // End of variables declaration//GEN-END:variables
}
