/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mephi.b22901.ekzamen;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ivis2
 */
public class StudentTaskRate extends javax.swing.JFrame {
    private final StudentResult report = new StudentResult();
    private ArrayList<Task> tasks;
    Variant variant;
    Student student;
    MainGUI mainGui;
    /**
     * Creates new form StudentTaskRate
     */
    public StudentTaskRate(Variant variant, Student student, MainGUI mainGui) {
        initComponents();
        setContentPane(studentRatePanel);
        setTitle("Задания варианта");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(700, 400);
        setLocationRelativeTo(null);
        setVisible(true);
        if (student.getReport() != null) {
            tasks = student.getReport().getTasks();
        } else tasks = variant.getTasks();
        fioLabel.setText(student.getFIO());
        variantLabel.setText(student.getVariant() + " вариант");
        updateTasksList();
        this.mainGui = mainGui;
        mainGui.setEnabled(false);
        rateButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentRatePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taskList = new javax.swing.JList();
        endRateButton = new javax.swing.JButton();
        studentLabel = new javax.swing.JLabel();
        fioLabel = new javax.swing.JLabel();
        variantInfoLabel = new javax.swing.JLabel();
        variantLabel = new javax.swing.JLabel();
        taskDescriptionLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        maxGradeLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        rateTextField = new javax.swing.JTextField();
        rateButton = new javax.swing.JButton();
        rateInfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cписок заданий:");

        taskList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        taskList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                taskListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(taskList);

        endRateButton.setText("Закончить выставление оценок");
        endRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endRateButtonActionPerformed(evt);
            }
        });

        studentLabel.setText("Студент:");

        fioLabel.setText(" ");

        variantInfoLabel.setText("Вариант:");

        variantLabel.setText(" ");

        taskDescriptionLabel.setText("Task description:");

        descriptionLabel.setText("  ");

        maxGradeLabel.setText("Max Rate:");

        gradeLabel.setText(" ");

        rateTextField.setText(" ");
        rateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateTextFieldActionPerformed(evt);
            }
        });

        rateButton.setText("Выставление оценки");
        rateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateButtonActionPerformed(evt);
            }
        });

        rateInfoLabel.setText("Оценка:");

        javax.swing.GroupLayout studentRatePanelLayout = new javax.swing.GroupLayout(studentRatePanel);
        studentRatePanel.setLayout(studentRatePanelLayout);
        studentRatePanelLayout.setHorizontalGroup(
            studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentRatePanelLayout.createSequentialGroup()
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentRatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(studentRatePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentRatePanelLayout.createSequentialGroup()
                                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(studentRatePanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(variantInfoLabel)
                                            .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(rateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rateInfoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rateTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(variantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(studentRatePanelLayout.createSequentialGroup()
                                        .addComponent(maxGradeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(studentRatePanelLayout.createSequentialGroup()
                                .addComponent(taskDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(studentRatePanelLayout.createSequentialGroup()
                                        .addComponent(endRateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        studentRatePanelLayout.setVerticalGroup(
            studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentRatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fioLabel))
                .addGap(18, 18, 18)
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(studentRatePanelLayout.createSequentialGroup()
                        .addComponent(variantInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(variantLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rateInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rateButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionLabel))
                .addGap(18, 18, 18)
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxGradeLabel)
                    .addComponent(gradeLabel))
                .addGap(13, 13, 13)
                .addComponent(endRateButton)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(studentRatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentRatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateButtonActionPerformed
        try {
            int selectedIndex = taskList.getSelectedIndex(); 
            if (selectedIndex == -1) {
                JOptionPane.showMessageDialog(this, "Пожалуйста, выберите задание в списке!","Ошибка",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            int grade = Integer.parseInt(rateTextField.getText());

            if (grade < 0) {
                JOptionPane.showMessageDialog(this, "Оценка не может быть отрицательной!","Ошибка",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (grade > tasks.get(selectedIndex).getMaxGrade()) {
                JOptionPane.showMessageDialog(this, "Оценка превышает максимальный балл","Ошибка",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            TaskRecord taskReport = new TaskRecord();
            taskReport.setGrade(grade);
            tasks.get(selectedIndex).setReport(taskReport);
            updateTasksList();
            rateButton.setEnabled(false);
        } catch (NumberFormatException exception) {
            JOptionPane.showMessageDialog(this, "Необходимо ввести целое число","Ошибка",
                    JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_rateButtonActionPerformed

    private void rateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateTextFieldActionPerformed

    }//GEN-LAST:event_rateTextFieldActionPerformed

    private void endRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endRateButtonActionPerformed
        if (tasks.stream().filter(task -> task.getReport() == null).findFirst().orElse(null) != null) {
            JOptionPane.showMessageDialog(StudentTaskRate.this, "Не все задания оценены","Ошибка",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            report.setTasks(tasks);
            mainGui.setEnabled(true);
            dispose();
        }
    }//GEN-LAST:event_endRateButtonActionPerformed

    private void taskListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_taskListValueChanged
        if (!evt.getValueIsAdjusting()) { 
            int selectedIndex = taskList.getSelectedIndex();
            rateTextField.setText("");
            rateTextField.setEnabled(true);
            rateButton.setEnabled(true);

            Task task = tasks.get(selectedIndex);

            if (task.getCondition().length() > 125) {
                descriptionLabel.setText(task.getCondition().substring(0, 125) + "-");
            } else {
                descriptionLabel.setText(task.getCondition());
            }
            if (task.getMaxGrade() > 4) {
                gradeLabel.setText(task.getMaxGrade() + " баллов");
            } else {
                gradeLabel.setText(task.getMaxGrade() + " балла");
            }

            if (task.getReport() != null) {
                rateTextField.setText(task.getReport().getGrade() + "");
            }
        }
    }//GEN-LAST:event_taskListValueChanged

    /**
     * @param args the command line arguments
     */
    private void updateTasksList() {
        DefaultListModel<Task> listModel = new DefaultListModel<>();
        for (Task task : tasks) {
            listModel.addElement(task);
        }
        taskList.removeListSelectionListener(taskList.getListSelectionListeners()[0]);
        taskList.setModel(listModel);
        taskList.addListSelectionListener(this::taskListValueChanged);
    }
    public StudentResult getReport() {
        return report;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton endRateButton;
    private javax.swing.JLabel fioLabel;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel maxGradeLabel;
    private javax.swing.JButton rateButton;
    private javax.swing.JLabel rateInfoLabel;
    private javax.swing.JTextField rateTextField;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JPanel studentRatePanel;
    private javax.swing.JLabel taskDescriptionLabel;
    private javax.swing.JList taskList;
    private javax.swing.JLabel variantInfoLabel;
    private javax.swing.JLabel variantLabel;
    // End of variables declaration//GEN-END:variables
}
