/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mephi.b22901.ekzamen;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * Графический интерфейс для оценки заданий выбранного варианта студента.
 * Позволяет выставлять оценки, комментарии и фиксировать результат.
 * Использует Swing-компоненты для взаимодействия с пользователем.
 * Отключает главное окно на время оценки.
 * 
 * @author Иван Исаев
 */
public class StudentTaskRate extends javax.swing.JFrame {
    /**
     * Итоговый результат студента с оцененными заданиями.
     */
    private final StudentResult report = new StudentResult();
    /**
     * Список заданий выбранного варианта или сохраненного отчета студента.
     */
    private ArrayList<Task> tasks;
    /**
     * Вариант заданий, выбранный для оценки.
     */
    Variant variant;
    /**
     * Студент, чьи задания оцениваются.
     */
    Student student;
    /**
     * Главное окно приложения, блокируется на время оценки.
     */
    MainGUI mainGui;
    /**
     * Создает новое окно для оценки заданий студента,
     * инициализирует все компоненты и загружает данные.
     * 
     * @param variant Вариант заданий.
     * @param student Студент, чьи задания оцениваются.
     * @param mainGui Главное окно приложения.
     */
    public StudentTaskRate(Variant variant, Student student, MainGUI mainGui) {
        initComponents();
        setContentPane(studentRatePanel);
        setTitle("Задания варианта");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(700, 600);
        setLocationRelativeTo(null);
        setVisible(true);
        if (student.getReport() != null) {
            tasks = student.getReport().getTasks();
        } else tasks = variant.getTasks();
        fioLabel.setText(student.getFIO());
        variantLabel.setText(student.getVariant() + " вариант");
        updateTasksList();
        this.mainGui = mainGui;
        mainGui.setEnabled(false);
        rateButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentRatePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taskList = new javax.swing.JList();
        studentLabel = new javax.swing.JLabel();
        fioLabel = new javax.swing.JLabel();
        variantInfoLabel = new javax.swing.JLabel();
        variantLabel = new javax.swing.JLabel();
        taskDescriptionLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        maxGradeLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        rateTextField = new javax.swing.JTextField();
        rateButton = new javax.swing.JButton();
        rateInfoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskDescriptionTextArea = new javax.swing.JTextArea();
        withoutCommentButton = new javax.swing.JButton();
        notCompletedTaskButton = new javax.swing.JButton();
        correctTaskButton = new javax.swing.JButton();
        endRateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cписок заданий:");

        taskList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        taskList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                taskListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(taskList);

        studentLabel.setText("Студент:");

        fioLabel.setText(" ");

        variantInfoLabel.setText("Вариант:");

        variantLabel.setText(" ");

        taskDescriptionLabel.setText("Текст задания:");

        descriptionLabel.setText("  ");

        maxGradeLabel.setText("Максимальная оценка:");

        gradeLabel.setText(" ");

        rateTextField.setText(" ");
        rateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateTextFieldActionPerformed(evt);
            }
        });

        rateButton.setText("Выставление оценки");
        rateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateButtonActionPerformed(evt);
            }
        });

        rateInfoLabel.setText("Оценка:");

        jLabel2.setText("Комментарий к заданию:");

        taskDescriptionTextArea.setColumns(20);
        taskDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(taskDescriptionTextArea);

        withoutCommentButton.setText("Без комментария");
        withoutCommentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withoutCommentButtonActionPerformed(evt);
            }
        });

        notCompletedTaskButton.setText("Задание не выполнено");
        notCompletedTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notCompletedTaskButtonActionPerformed(evt);
            }
        });

        correctTaskButton.setText("Задание выполнено корректно");
        correctTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctTaskButtonActionPerformed(evt);
            }
        });

        endRateButton.setText("Закончить выставление оценок");
        endRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endRateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentRatePanelLayout = new javax.swing.GroupLayout(studentRatePanel);
        studentRatePanel.setLayout(studentRatePanelLayout);
        studentRatePanelLayout.setHorizontalGroup(
            studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentRatePanelLayout.createSequentialGroup()
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentRatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(studentRatePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentRatePanelLayout.createSequentialGroup()
                                .addComponent(taskDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(studentRatePanelLayout.createSequentialGroup()
                                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(studentRatePanelLayout.createSequentialGroup()
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(variantInfoLabel)
                                                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(rateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(rateInfoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(rateTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addComponent(variantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(studentRatePanelLayout.createSequentialGroup()
                                            .addComponent(maxGradeLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(studentRatePanelLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane1)))
                                    .addGroup(studentRatePanelLayout.createSequentialGroup()
                                        .addComponent(withoutCommentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(endRateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(studentRatePanelLayout.createSequentialGroup()
                                                .addComponent(notCompletedTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(correctTaskButton)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        studentRatePanelLayout.setVerticalGroup(
            studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentRatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fioLabel))
                .addGap(18, 18, 18)
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(studentRatePanelLayout.createSequentialGroup()
                        .addComponent(variantInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(variantLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rateInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rateButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionLabel))
                .addGap(18, 18, 18)
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxGradeLabel)
                    .addComponent(gradeLabel))
                .addGap(18, 18, 18)
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withoutCommentButton)
                    .addComponent(correctTaskButton)
                    .addComponent(notCompletedTaskButton))
                .addGap(18, 18, 18)
                .addComponent(endRateButton)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(studentRatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(studentRatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Обрабатывает нажатие кнопки для сохранения оценки выбранного задания.
     *
     * @param evt Событие нажатия кнопки.
     */
    private void rateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateButtonActionPerformed
        try {
            int selectedIndex = taskList.getSelectedIndex(); 
            if (selectedIndex == -1) {
                JOptionPane.showMessageDialog(this, "Пожалуйста, выберите задание в списке!","Ошибка",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            int grade = Integer.parseInt(rateTextField.getText());

            if (grade < 0) {
                JOptionPane.showMessageDialog(this, "Оценка не может быть отрицательной!","Ошибка",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (grade > tasks.get(selectedIndex).getMaxGrade()) {
                JOptionPane.showMessageDialog(this, "Оценка превышает максимальный балл","Ошибка",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            Task task = tasks.get(selectedIndex);
            TaskRecord taskReport = task.getReport() != null ? task.getReport() : new TaskRecord();
            taskReport.setGrade(grade);
            if (!taskDescriptionTextArea.getText().trim().isEmpty()) {
                taskReport.setComment(taskDescriptionTextArea.getText().trim());
            }

            task.setReport(taskReport);
            updateTasksList();
            rateButton.setEnabled(false);

            setCommentButtonsEnabled(true);
        } catch (NumberFormatException exception) {
            JOptionPane.showMessageDialog(this, "Необходимо ввести целое число","Ошибка",
                    JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_rateButtonActionPerformed

    private void rateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateTextFieldActionPerformed

    }//GEN-LAST:event_rateTextFieldActionPerformed
    /**
     * Завершает процесс оценки всех заданий студента.
     * Проверяет, все ли задания оценены, и закрывает окно.
     *
     * @param evt Событие нажатия кнопки.
     */
    private void endRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endRateButtonActionPerformed
        if (tasks.stream().filter(task -> task.getReport() == null).findFirst().orElse(null) != null) {
            JOptionPane.showMessageDialog(StudentTaskRate.this, "Не все задания оценены","Ошибка",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            report.setTasks(tasks);
            mainGui.setEnabled(true);
            dispose();
        }
    }//GEN-LAST:event_endRateButtonActionPerformed
    /**
     * Обрабатывает выбор задания из списка.
     * Отображает подробности задания и текущую оценку.
     *
     * @param evt Событие выбора элемента списка.
     */
    private void taskListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_taskListValueChanged
        if (!evt.getValueIsAdjusting()) {
            int selectedIndex = taskList.getSelectedIndex();
            if (selectedIndex == -1) return;

            Task task = tasks.get(selectedIndex);

            rateTextField.setText("");
            rateTextField.setEnabled(true);
            rateButton.setEnabled(true);

            if (task.getReport() != null && task.getReport().getGrade() >= 0) {
                rateTextField.setText(String.valueOf(task.getReport().getGrade()));
                rateButton.setEnabled(false);
            }

            taskDescriptionTextArea.setText(
                task.getReport() != null && task.getReport().getComment() != null 
                    ? task.getReport().getComment() 
                    : ""
            );

            descriptionLabel.setText(
                task.getCondition().length() > 125 
                    ? task.getCondition().substring(0, 125) + "-" 
                    : task.getCondition()
            );

            gradeLabel.setText(task.getMaxGrade() + (task.getMaxGrade() > 4 ? " баллов" : " балла"));
        }
    }//GEN-LAST:event_taskListValueChanged
    /**
     * Удаляет комментарий у выбранного задания.
     *
     * @param evt Событие нажатия кнопки.
     */
    private void withoutCommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withoutCommentButtonActionPerformed
        int selectedIndex = taskList.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Выберите задание!", "Ошибка", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Task task = tasks.get(selectedIndex);
        if (task.getReport() == null) {
            task.setReport(new TaskRecord());
        }

        task.getReport().setComment(null);
        taskDescriptionTextArea.setText("");

        rateButton.setEnabled(true);
        JOptionPane.showMessageDialog(this, "Комментарий удален", "Информация", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_withoutCommentButtonActionPerformed
    /**
     * Устанавливает для выбранного задания 0 баллов и комментарий о невыполнении.
     *
     * @param evt Событие нажатия кнопки.
     */
    private void notCompletedTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notCompletedTaskButtonActionPerformed
        int selectedIndex = taskList.getSelectedIndex(); 
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Выберите задание!", "Ошибка", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Task task = tasks.get(selectedIndex);

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Вы уверены, что хотите поставить 0 баллов за это задание?\n(Это перезапишет текущую оценку)",
            "Подтверждение",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            TaskRecord report = task.getReport() != null ? task.getReport() : new TaskRecord();

            report.setGrade(0);
            report.setComment("Задание не выполнено");
            task.setReport(report);

            rateTextField.setText("0");
            taskDescriptionTextArea.setText("Задание не выполнено");
            rateButton.setEnabled(false); 

            updateTasksList();

            JOptionPane.showMessageDialog(this, 
                "Заданию установлено 0 баллов", 
                "Информация", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_notCompletedTaskButtonActionPerformed
    /**
     * Выставляет максимальный балл и комментарий о корректном выполнении для выбранного задания.
     *
     * @param evt Событие нажатия кнопки.
     */
    private void correctTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctTaskButtonActionPerformed
        int selectedIndex = taskList.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Выберите задание!", "Ошибка", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Task task = tasks.get(selectedIndex);
        int maxGrade = task.getMaxGrade();

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Поставить максимальный балл (" + maxGrade + ") за это задание?",
            "Подтверждение",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            TaskRecord taskReport = task.getReport() != null ? task.getReport() : new TaskRecord();

            taskReport.setGrade(maxGrade);
            String comment = "Задание выполнено корректно";
            taskReport.setComment(comment);
            task.setReport(taskReport);

            rateTextField.setText(String.valueOf(maxGrade));
            taskDescriptionTextArea.setText(comment);
            updateTasksList();
            rateButton.setEnabled(false);
        } else {
            String comment = "Задание выполнено корректно";
            if (task.getReport() == null) {
                task.setReport(new TaskRecord());
            }
            task.getReport().setComment(comment);
            taskDescriptionTextArea.setText(comment);

            setCommentButtonsEnabled(false);
        }
    }//GEN-LAST:event_correctTaskButtonActionPerformed

    /**
     * Обновляет список заданий в интерфейсе.
     */
    private void updateTasksList() {
        DefaultListModel<Task> listModel = new DefaultListModel<>();
        for (Task task : tasks) {
            listModel.addElement(task);
        }
        taskList.removeListSelectionListener(taskList.getListSelectionListeners()[0]);
        taskList.setModel(listModel);
        taskList.addListSelectionListener(this::taskListValueChanged);
    }
    /**
     * Возвращает результат оценки студента.
     *
     * @return Результат с оценёнными заданиями.
     */
    public StudentResult getReport() {
        return report;
    }
    /**
     * Включает или отключает кнопки для быстрой установки комментариев.
     *
     * @param enabled true, если кнопки должны быть активны; false иначе.
     */
    private void setCommentButtonsEnabled(boolean enabled) {
        correctTaskButton.setEnabled(enabled);
        notCompletedTaskButton.setEnabled(enabled);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton correctTaskButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton endRateButton;
    private javax.swing.JLabel fioLabel;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel maxGradeLabel;
    private javax.swing.JButton notCompletedTaskButton;
    private javax.swing.JButton rateButton;
    private javax.swing.JLabel rateInfoLabel;
    private javax.swing.JTextField rateTextField;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JPanel studentRatePanel;
    private javax.swing.JLabel taskDescriptionLabel;
    private javax.swing.JTextArea taskDescriptionTextArea;
    private javax.swing.JList taskList;
    private javax.swing.JLabel variantInfoLabel;
    private javax.swing.JLabel variantLabel;
    private javax.swing.JButton withoutCommentButton;
    // End of variables declaration//GEN-END:variables
}
